version: '3.9'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks: 
      jenkins-network:
        aliases:
          - docker
    expose:
      - "2376"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    command: --storage-driver overlay2

  jenkins-blueocean:
    build: ./docker/jenkins/
    container_name: jenkins-blueocean
    restart: on-failure
    networks: 
      - jenkins-network
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

networks:
  jenkins-network:

volumes:
  jenkins-docker-certs:
  jenkins-data: